### ISSUE TITLE
Non-existent Chisel Commit

### ISSUE THREAD

**Issue by seldridge** [ucb-bar/rocket-chip#19]
It looks like the Chisel submodule is now pointing at an invalid commit ID (ededc302ed1fc9ba9d583cf32d50deec55683952).

**Comment by ccelio** [comment]
Thanks for the heads-up. I assume a push to rocket-chip occurred without a corresponding push to Chisel! Should be fixed shortly.

**Comment by aswaterman** [comment]
Yep.  Sorry about that.

On Wed, Sep 30, 2015 at 4:19 PM, Christopher Celio <notifications@github.com
