### ISSUE TITLE
Clock vs. clk in TopIO()

### ISSUE THREAD

**Issue by mwachs5** [ucb-bar/rocket-chip#218]
This is related to : https://github.com/ucb-bar/chisel3/issues/258

The Chisel name for clock is 'clock' and 'reset'.  But some top-level ports on rocket-chip use 'clk' and 'rst'. This inconsistency is a minor annoyance when instantiating the block.

@terpstra

**Comment by hcook** [comment]
Closed by #320 h/t @aswaterman
