### ISSUE TITLE
Connecting Coreplex Interrupts directly to Periphery

### ISSUE THREAD

**Issue by mwachs5** [ucb-bar/rocket-chip#219]
Currently the only source of PLIC interrupts is from TopIO . In other words, interrupts can not come from the Periphery without doing some connection outside the Top level.

I suggest that we split NExtInterrupts parameter into 2 parts. The default parameters as follows:

NTopExtInterrupts = <whatever NExtInterrupts default is>
NPeripheryExtInterrupts = 0 
NExtInterrupts = site(NTopInterrupts) + site(NPeripheryInterrupts).

Within Top there would be a wiring convention that Periphery Interrupts are the lower PLIC bits and Top interrupts are at the upper PLIC bits (or maybe there is some elaborate mapping but that's not as clear in my mind).

The current functionality remains the same if you want it, this would just automate some common-case wiring.

I plan to implement this but happy for any feedback.

**Comment by aswaterman** [comment]
sounds reasonable to me
