### ISSUE TITLE
Heterogeneous core configs cannot generate the correct config string

### ISSUE THREAD

**Issue by colinschmidt** [ucb-bar/rocket-chip#232]
The way the config string is created currently only looks at one of the core's parameters for things like what isa is supported.
rocket-chip should be able to handle the creation of heterogeneous ISA cores including the correct config string.

**Comment by aswaterman** [comment]
This is already on the docket.

**Comment by colinschmidt** [comment]
Cool. It would also be useful if the RoCCParameters included an extension name. Then just add something like the following to the isa string as well.

```
${site(BuildRoCC).map(_.xName).mkString}
```

**Comment by aswaterman** [comment]
Agreed.  We plan to standardize how components register themselves in the config string & address map (it's quite ad hoc now); RoCC should use that mechanism once it exists.
