### ISSUE TITLE
Add test to regression for MMIO + Scratchpad

### ISSUE THREAD

**Issue by mwachs5** [ucb-bar/rocket-chip#256]
There is an issue with routing to the external MMIO port if you also have a Scratchpad. @yunsup  is working on a fix, but we should also add a test to the regression for this case.

**Comment by zhemao** [comment]
Really, we need more tests of MMIO in general. I guess I can add a cache regression test which tries to write out to MMIO passing through the L1.

**Comment by zhemao** [comment]
So what's the bug? If you have a scratchpad and try to make an MMIO request, what happens?

**Comment by mwachs5** [comment]
This was fixed already by commit 8536a2a But it wasn't caught in the regression.

**Comment by mwachs5** [comment]
The bug there was that if you had a scratchpad at 0x8000_0000, because it was in 'int:' memory region, the 'int' memory region spanned the MMIO devices at say 0x5000_0000, so at runtime you'd get 'no possible route' assertion failure.

**Comment by terpstra** [comment]
This has been fixed by replacing all the TL1 crossbars with TL2. The scratchpad is routed just like any other device.
