### ISSUE TITLE
GLIBC version used 

### ISSUE THREAD

**Issue by nitish2112** [ucb-bar/rocket-chip#26]
Hi, 

  I am having some issues while compiling the design using VCS. The errors are coming from the g++ invocation by VCS. Can you please tell which version of glibc was used for the project. The one I am using is:

%ldd --version

ldd (Ubuntu EGLIBC 2.15-0ubuntu10.12) 2.15
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

 Thanks a lot :)

**Comment by ben-k** [comment]
Looks like we are (typically) using glibc version 2.19.

**Comment by colinschmidt** [comment]
Re-open this if you are still having an issue. Please include the error log from g++ failing to compile when/if you do.
