### ISSUE TITLE
emulator doesn't set STOP_COND

### ISSUE THREAD

**Issue by colinschmidt** [ucb-bar/rocket-chip#267]
Currently when you build your design in the emulator it does not set the STOP_COND variable so any asserts that occur during reset will cause the simulation to fail.

In vsim STOP_COND and PRINTF_COND are both set to values from the TestDriver, which does not exist in emulator.

**Comment by colinschmidt** [comment]
I'm going to look into this a little bit but if anyone else has a better idea of what the solution should be let me know.

**Comment by colinschmidt** [comment]
Ok it actually wasn't difficult. submitting a PR as soon as the tests pass.

**Comment by aswaterman** [comment]
I take it you're handling it similarly to how the emulator handles PRINTF_COND?

**Comment by zhemao** [comment]
This got fixed right? Can I close the issue?

**Comment by colinschmidt** [comment]
Yup.
