### ISSUE TITLE
TestHarness and Rocket default VLSI port mismatch

### ISSUE THREAD

**Issue by weidongye** [ucb-bar/rocket-chip#27]
Hi,

I am trying to run VCS with the latest rocketTestHarness.

I run make -j16 run in rocket-chip/vsim, and I get many of these errors: Lint-[TFIPC-L] Too few instance port connections.

Is this only an issue on my end? Please help.

Thanks,
Weidong

**Comment by ben-k** [comment]
This is expected behavior, as not all modules have all ports connected in the design.  vcs should still run despite the messages from its linter - the flags passed to vcs via the Makefile/Makefrag should tell vcs to tolerate them.

**Comment by weidongye** [comment]
I see thanks!
