### ISSUE TITLE
SmiIO: can it be removed?

### ISSUE THREAD

**Issue by hcook** [ucb-bar/rocket-chip#280]
Is anyone still using junctions.SmiIO or can this be removed?

**Comment by colinschmidt** [comment]
Hurricane no longer uses SmiIO. I believe we were the only consumer.

**Comment by jackbackrack** [comment]
actually we did use this for our RISC-V workshop chisel tutorial.
is there an equivalent functionality for adding "simple memory interface"
like peripherals?

**Comment by aswaterman** [comment]
Yes - @terpstra made a TileLink-to-control-register interface that is more flexible and still concise.  Better just to support one thing, IMO.

**Comment by jackbackrack** [comment]
sounds good.

**Comment by colinschmidt** [comment]
@aswaterman Where does this interface live?

**Comment by aswaterman** [comment]
that is a question for @terpstra

**Comment by terpstra** [comment]
It lives in uncore/tilelink2/Example.scala
