### ISSUE TITLE
Doubt regarding DMA controller

### ISSUE THREAD

**Issue by prashantrar** [ucb-bar/rocket-chip#36]
I saw this new configuration in configs.scala as shown below

<b>
class WithDmaController extends Config(
  (pname, site, here) => pname match {
    case UseDma => true
    case BuildRoCC => Seq(
        RoccParameters(
          opcodes = OpcodeSet.custom2,
          generator = (p: Parameters) => Module(new DmaController()(p)),
          useDma = true))
    case RoccMaxTaggedMemXacts => 1
  })
</b>

I can see that the custom2 opcode is being mapped to DmaController() but i am unable to see the definition of DmaController in rocc.scala. Where is it defined

**Comment by zhemao** [comment]
DmaController is in dma.scala, not rocc.scala. However, the DMA API is still in a bit of flux. We'll release a formal ISA document at some point. Please hold off on using it until then.
