### ISSUE TITLE
Unable to run c code when FPU is disabled in rocket chip.

### ISSUE THREAD

**Issue by prashantrar** [ucb-bar/rocket-chip#37]
I wrote a c code and compiled it with riscv64-unknown-elf-gcc and ran it on the rocket chip instantiated on a zedboard using the proxy kernel and front end server(./fesvr-zynq pk <binary>).

The same binary works on the zedboard when the fpu is enabled from configs.scala but the binary just doesn't execute when the fpu is disabled.

**Comment by palmer-dabbelt** [comment]
There isn't enough information to fix this.  Did you:
* Try building a "--disable-float" version of the toolchain?
* Try running your code in Spike without an FPU?
* Try running your code in RTL simulation without an FPU?
