### ISSUE TITLE
Is io.resp.data in rocket/icache.scala even used?

### ISSUE THREAD

**Issue by jackkoenig** [ucb-bar/rocket-chip#408]
From

``` scala
class ICacheResp(implicit p: Parameters) extends CoreBundle()(p) with HasL1CacheParameters {
  val data = Bits(width = coreInstBits)
  val datablock = Bits(width = rowBits)
}
```

As far as I can tell, only datablock is used.

**Comment by ccelio** [comment]
Is it not? I've never seen datablock before, but I use data in BOOM.

https://github.com/ucb-bar/riscv-boom/blob/master/src/main/scala/fetch.scala#L129

**Comment by colinschmidt** [comment]
Hwacha uses datablock

**Comment by colinschmidt** [comment]
@ccelio I think you are instantiating the frontend not the ICache itself so thats why you use data and not datablock. Hwacha has its own frontend and so instantiates the actual ICache to use its datablock.

**Comment by ccelio** [comment]
Oh, good point.
