### ISSUE TITLE
Cannot generate an instance of rocket-chip with 0 top-level interrupts

### ISSUE THREAD

**Issue by davidbiancolin** [ucb-bar/rocket-chip#436]
In fpga-zynq, we use a configuration of rocket-chip that presents no external interrupts at the top level. 

Omitting PeripheryExtInterrupts{ , Bundle, Module} in the ExampleTop cake (as we have done previously), or alternatively setting NTopExtInterrupts = 0 both produce exceptions. 

Given the trivial workaround, this is not critical but it does represent regression from commit 5392219 (the current head of submodule in fpga-zynq).

**Comment by aswaterman** [comment]
agreed, there's no good reason not to support this case.

**Comment by terpstra** [comment]
I'll look into this as soon as we're done the L1 conversion.

**Comment by terpstra** [comment]
Fixed in commit 5b594ced293f323323611ca65de80b59d55ab959.
