### ISSUE TITLE
Cross the external AXI ports to a foreign clock domain

### ISSUE THREAD

**Issue by hcook** [ucb-bar/rocket-chip#465]
We need to re-add the capability to cross the external AXI ports to a foreign clock domain.

**Comment by terpstra** [comment]
Why?

For our SoCs we swallow AXI IP inside Chisel-land, and the crossing (if any is needed) happens where it's connected. This scenario does not use the external port at all.

The case where the external port makes sense is when someone is integrating our core into a larger non-Chisel SoC. In that scenario, we want to let the person integrating our core decide whether or not to cross domains. Maybe they will want to run the other side synchronously for performance.
