### ISSUE TITLE
Should we make ExtMem and ExtBus more easily configurable?

### ISSUE THREAD

**Issue by hcook** [ucb-bar/rocket-chip#466]
Currently BasePlatformConfig includes MasterConfig fields for ExtMem and ExtBus, but we don't provide helper WithConfigs for overriding them. Should we?

**Comment by hcook** [comment]
The specific user feature request was to override the base address of ExtMem

**Comment by zhemao** [comment]
It definitely makes sense to make the external memory size configurable. Then it can be adjusted to match the size of the actual backing memory.

**Comment by terpstra** [comment]
My main concern is that we will need multiple fragments of memory for more
than 2GB machines. So the right answer on how to generealize membase is not
just adding a with config.

**Comment by terpstra** [comment]
@hcook You and other Henry have some patchset that fixes this, right?

**Comment by davidbiancolin** [comment]
For what it's worth, we're interested in configurations with >2 GB here at Berkeley.
