### ISSUE TITLE
How can I get a 32 bit RISC-V core

### ISSUE THREAD

**Issue by lintonghit** [ucb-bar/rocket-chip#499]
How can I get a 32 bit RISC-V core? 
Which CONFIG should i change?

**Comment by aswaterman** [comment]
The XLen parameter is what you're looking for (it can handle the values 32 and 64).

**Comment by lintonghit** [comment]
@aswaterman 

Where to change the XLen parameter ? in "roceket.scala"?

**Comment by ben-k** [comment]
Take a look at src/main/scala/coreplex/Configs.scala.
