### ISSUE TITLE
Is ScalaDoc documentation available?

### ISSUE THREAD

**Issue by MarcoGeuna** [ucb-bar/rocket-chip#500]
Hi all,

Do you have available some documentation that explains how your packages and their classes, traits etc are organized, and their methods? I'm thinking about something like ScalaDocs...I found only [this](https://chisel.eecs.berkeley.edu/api/#package) about Chisel, and [this](https://github.com/ucb-bar/uncore) about uncore package. What about all the other packages?

Thanks!

**Comment by ben-k** [comment]
Alas, such documentation does not exist (though it would sure be nice!).  Also, be careful - the uncore submodule that you linked to is an old, deprecated version.

Hopefully there will be less churn in the codebase going forward and so comprehensive documentation will become feasible.

**Comment by MarcoGeuna** [comment]
Ok! Thank you for your answer!
