### ISSUE TITLE
Which VCS versions are supported?

### ISSUE THREAD

**Issue by preyas3359** [ucb-bar/rocket-chip#501]
Hi,

Can you please let me know which all VCS versions are supported for vsim simulations? I currently have 2012 version of VCS, it was working fine with Chisel2. But I am not able to build using the same version with Chisel3 variant. 

Can somebody help?

Thanks and Regards,
Preyas

**Comment by colinschmidt** [comment]
Can you post the error you get? I've used 2014 and newer recently.

**Comment by preyas3359** [comment]
Hi Colin,

It looks like some weird license related issue in my institution. Sorry for false alarm. I will keep refile the issue if it persists post local license is resolved.

Thanks.

Regards,
Preyas
