### ISSUE TITLE
vlsi_mem_gen: Broken with python3

### ISSUE THREAD

**Issue by mox-mox** [ucb-bar/rocket-chip#510]
b4cd8c5981337be4086680c687dc219c7013fc22 Fixes most of vlsi_mem_gen for python3. However,  parse_line(line) returns (along other values) a fraction (width/mask_gran) which will cause an error when fed into gen_mem: 
    
    TypeError: 'float' object cannot be interpreted as an integer
    
To solve this, one could either make the file a python2-script, or force the fraction to be an integer, using the int function:
    
    return (name, width, depth, mask_gran, int(width/mask_gran), ports)
    
instead of
    
    return (name, width, depth, mask_gran, width/mask_gran, ports)
    
Best regards,
mox

**Comment by hcook** [comment]
Closed by #493
