### ISSUE TITLE
Program counter start address

### ISSUE THREAD

**Issue by toschmmd** [ucb-bar/rocket-chip#535]
The rocket github readme and this paper from 2013 
http://www-inst.eecs.berkeley.edu/~cs250/fa13/handouts/lab2-riscv.pdf
suggest that the program counters start address is 0x2000

However, i just modified the rocket chip in the fpga-zynq git repository to access the program counter in a debug view and saw that the program counter always starts as 0x800

Am i missing something obvious?

**Comment by ben-k** [comment]
The document you linked is old and out-of-date, and doesn't correspond to any of the current specifications or code.  Similarly, the ucb-bar/rocket submodule is deprecated.
