### ISSUE TITLE
Skip Travis builds on non-functional PRs

### ISSUE THREAD

**Issue by jackkoenig** [ucb-bar/rocket-chip#553]
PRs like https://github.com/ucb-bar/rocket-chip/pull/530 just eat Travis bandwidth.

This could probably be accomplished by adding a tag to commits like [non-functional] and having the Travis script just pass if it sees that. This of course relies on reviewers verifying that the changes are non-functional.

**Comment by jackkoenig** [comment]
It looks like this functionality exists by putting `[ci skip]` or `[skip ci]`: https://docs.travis-ci.com/user/customizing-the-build#Skipping-a-build

In my opinion, we should take advantage of this.

**Comment by terpstra** [comment]
We have gotten travis build times back down to 35 minutes and we only build on PR pushes, so I think wasted Travis bandwidth is not much of an issue anymore. Nevertheless, yes we should endeavor not to waste build time either by marking commits as you suggested or just not pushing a branch to a PR unless we want it built (which is what I think most people are doing).
