### ISSUE TITLE
Deprecation warning about "debug" in Chisel

### ISSUE THREAD

**Issue by mwachs5** [ucb-bar/rocket-chip#604]
https://github.com/ucb-bar/rocket-chip/blob/master/src/main/scala/groundtest/Comparator.scala#L296

[warn] rocket-chip/src/main/scala/groundtest/Comparator.scala:296: object debug in package Chisel is deprecated: debug doesn't do anything in Chisel3 as no pruning happens in the frontend
[warn]   debug(idx)

Can we remove the code to get rid of the warning?

**Comment by aswaterman** [comment]
I deleted this on my branch, so it'll be gone soon.
