### ISSUE TITLE
rocket-chip/riscv-tools spike pk hello : fail to run , no such file or directory , child dtb process failed 

### ISSUE THREAD

**Issue by Peach92** [ucb-bar/rocket-chip#644]
My os is Ubuntu 14.04 gcc5.4 g++5.4 

git clone https://github.com/ucb-bar/rocket-chip.git
cd rocket-chip
git submodule update --init 
cd riscv-tools
git submodule update --init --recursive
export RISCV=/rocket-chip folder/riscv-tools/riscv
export PATH=$PATH:$RISCV/bin
./build.sh

It says something like '.....Toolchain compledted....'
I can compile hello.c by using the command "riscv64-unknown-elf-gcc -o hello hello.c" The hello object file is sucessfully generated.
However, when I execute "spike pk hello" it returns "Failed to run : No such file or directory Child dtb process failed"

I tried at least thress times and have the same problem every time.

**Comment by aswaterman** [comment]
You need to install dtc.  On Ubuntu, use ```sudo apt-get install device-tree-compiler```.

**Comment by Peach92** [comment]
Thanks. I am very grateful for your help. but when I 
sudo apt-get install device-tree-compiler
./build.sh

It returns another "Failed to run : No such file or directory Child dts process failed"
