### ISSUE TITLE
Package Dependency List(s) should be added to README

### ISSUE THREAD

**Issue by mwachs5** [ucb-bar/rocket-chip#669]
There isn't a package dependency list in this repo, though users need to install various things like javac and dtc. Some may be covered by Chisel3 / Firrtl README, but the latter probably isn't. Should we add something to the README about this?

**Comment by aswaterman** [comment]
riscv-tools' README has the package list depended upon by the toolchain (including dtc).  To avoid having to keep them in sync, maybe we have rocket-chip's README refer to that and Chisel's READMEs?

**Comment by mwachs5** [comment]
Yes, I think we should refer to the other READMEs if they exist. But it seems like DTC is our own dependency?

**Comment by mwachs5** [comment]
Oh sorry I retract my statement if riscv-tools includes dtc

**Comment by aswaterman** [comment]
yeah i just checked, it does

**Comment by mwachs5** [comment]
closed by #670

**Comment by sorear** [comment]
rocket-chip master depends on dtc.

riscv-tools priv-1.10 README mentions dtc.

riscv-tools master README does NOT mention dtc.

rocket-chip master has a README which points at riscv-tools' master README.

_If you follow links from the rocket-chip master README, you will not install all of the tools needed to build rocket-chip master._
