### ISSUE TITLE
Dumps and instructions

### ISSUE THREAD

**Issue by dplbsd** [ucb-bar/rocket-chip#7]
Hi everyone, and thanks for your work.

I'm doing "homework" with the rocket chip, we'd like to understand, and even help with the coherence protocols. Initially, we wanted to implement MOESI, but we're seeing we're out of time for that.

So, let's get to the "issue", whenever I compile the cycle precise emulator, and test it with the tests found at riscv-tools/riscv-tests, I get a dump, which, AFAIK, corresponds to the writeback stage. In the example you show at the README.md, at the end, there's the decoded instruction. But whenever I execute any test, I don't get any of these.

Is this feature implemented somewhere? 
If not, I'll probably write it myself, where do you think it should be added?
Thanks!

**Comment by ccelio** [comment]
Can you be more clear? What do you mean by "I don't get any of these."? 

When you run the emulator, you need to pass it the "+verbose" flag so it will print the Chisel printfs to stdout. And you need to have compiled the spike-dasm binary (a part of the riscv-tools) to convert the DASM(%x) string to a disassembled instruction.
