### ISSUE TITLE
spike pk hello error

### ISSUE THREAD

**Issue by xinjic** [ucb-bar/rocket-chip#721]
[jinxin@localhost riscv-tools]$ spike pk hello
Failed to run : No such file or directory
Child dts process failed

So,how to deal with it? It seems that something is wrong with DTC......
Thanks!

**Comment by zqcawzs** [comment]
Hi, have you settled this problem? I have the same too and have no idea how to fix it...

**Comment by aswaterman** [comment]
You need to install Device Tree Compiler (in Ubuntu, it's in the device-tree-compiler package).

**Comment by zqcawzs** [comment]
Thanks for help
